### ISSUE TITLE
Snap apps are missing after installing zsh

### ISSUE THREAD

**Issue by beastboicodes** [manavendrasen/dotfiles#1]
Apps installed using snap like vscode, pycharm and postman are missing. The folders are still present.
```
snap refresh
```
works fine.

snap version -
```
snap    2.45
snapd   2.45
series  16
neon    18.04
kernel  5.3.0-53-generic
```

**Comment by manavendrasen** [comment]
```
# in /etc/zsh/zshenv
emulate sh -c 'source /etc/profile.d/apps-bin-path.sh'
```
This [post](https://www.realjenius.com/2020/01/12/kde-neon-snap-apps-missing/) explains it.
